### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by eraigosa**
how to use it, I had some trouble finding the proj_lib variable solution.

Please provide enough information so that others can review your pull request:

just a comment of how to use it in .net

### CODE REVIEW

**Comment by MaxRev-Dev** [comment]
I thought, usage simple - install required runtime libraries (one or both) and a core package.

GDAL 3.0 has method to set proj6 path.
I had wrote this patch for initialization. It searches for shared library from package relative path.
https://github.com/MaxRev-Dev/gdal.netcore/blob/master/compile/Proj6Configure.cs#L36
Which error is thrown in your app?

**Comment by MaxRev-Dev** [comment]
I forgot to mention in docs, but in nuget package description there is a comment how to initialize runtime. Did you called?
`MaxRev.Gdal.Core.GdalBase.ConfigureAll();`

**Comment by eraigosa** [comment]
I also did some modifications to the readme file (this is the PR (pull request) I sent... so I have conflict with the readme you just add... but it is ok, I can discard my changes.
--------
this was the error... "cant find proj.db" and now I know that is a very easy solution, but it took me some time to have it ready in windows and Linux... please read my readme file modifications before i delete the PR
image

**Comment by eraigosa** [comment]
By the way... thanks for the library. it helped me to read a GDB file I needed to understand.

**Comment by MaxRev-Dev** [comment]
I've read your notes in this PR, my fault I didn't described the usage earlier. Hope that everything is clear now in docs)

**Comment by eraigosa** [comment]
I'd add a note telling people to configure the PROJ_LIB variable... but the new readme is ok... thanks man... bye.

**Comment by MaxRev-Dev** [comment]
Thanks for your feedback.
As I said before, core package already has it's own initializer for a proj library. So it's not necessary to set paths manually and restart your IDE every time to configure the environment.

**Pull request closed without merging**
